services:
  frontend:
    build: ./to-do-list
    ports: ["3001:3000"]
    depends_on:
      - backend
    volumes:
      - ./to-do-list:/app
      - /app/node_modules
    command: npm run dev

  backend:
    build: ./to-do-list-api
    ports: ["3000:3000"]
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/todolist
    volumes:
      - ./to-do-list-api:/app
      - /app/node_modules
    command: npm run start:dev

  mongodb:
    image: mongo:7
    ports: ["27017:27017"]
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
